# -*- coding: utf-8 -*-
"""Training_CarPrice&SaleProb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBa6T5bA7kMepv8fLWgtIdbTzOKrpZMY
"""
#Authors: Ahmet Alp Malkoç, Ceren Kızılırmak
# CMPE-442 Car Price Prediction and Sale Probability
from google.colab import files
uploaded = files.upload()  # Upload the dataset.zip file here
import zipfile
with zipfile.ZipFile("dataset.zip", "r") as zip_ref:
    zip_ref.extractall("dataset")

import os

for root, dirs, files in os.walk("dataset"):
    print("📁", root)
    for file in files:
        print("   └──", file)

import glob
import pandas as pd


# Try non-recursive
csv_files = glob.glob("dataset/*.csv")

# Try recursive
if not csv_files:
    csv_files = glob.glob("dataset/**/*.csv", recursive=True)

print("CSV files found:", csv_files)

if csv_files:
    df_list = [pd.read_csv(f) for f in csv_files]
    df = pd.concat(df_list, ignore_index=True)
    print("✅ Combined DataFrame shape:", df.shape)
else:
    print("❌ No CSV files found. Check your path and folder structure.")

# Show the result
df.head()

# Check missing values
df.isnull().sum()

# Drop the duplicate 'tax(£)' column (keep only 'tax')
if 'tax(£)' in df.columns:
    df.drop(columns=['tax(£)'], inplace=True)

# Impute missing numerical values using median
df['tax'] = df['tax'].fillna(df['tax'].median())
df['mpg'] = df['mpg'].fillna(df['mpg'].median())

# Confirm cleanup
df.isnull().sum()

# Regenerate merged DataFrame with 'Brand' column
df_list = []
for f in csv_files:
    brand = os.path.basename(f).split('.')[0]
    temp_df = pd.read_csv(f)
    temp_df['Brand'] = brand
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

# Reapply preprocessing steps on this new df
df.drop(columns=['tax(£)'], errors='ignore', inplace=True)
df['tax'] = df['tax'].fillna(df['tax'].median())
df['mpg'] = df['mpg'].fillna(df['mpg'].median())
df.head()

X = df.drop(columns=['price'])
y = df['price']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Numerical and categorical features
num_features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
cat_features = ['model', 'transmission', 'fuelType', 'Brand']

# Transformers
num_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])
cat_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combined preprocessing
preprocessor = ColumnTransformer(transformers=[
    ('num', num_transformer, num_features),
    ('cat', cat_transformer, cat_features)
])

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
import numpy as np

# Sample
X_train_sample = X_train.sample(10000, random_state=42)
y_train_sample = y_train.loc[X_train_sample.index]

# Define faster models
models = {
    'LinearRegression': LinearRegression(),
    'RandomForest': RandomForestRegressor(n_estimators=50, max_depth=5, random_state=42),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=50, max_depth=5, random_state=42)
}

results = {}
for name, model in models.items():
    pipe = make_pipeline(preprocessor, model)
    rmse_scores = cross_val_score(pipe, X_train_sample, y_train_sample, cv=3, scoring='neg_root_mean_squared_error', n_jobs=-1)
    results[name] = {
        'RMSE (CV mean)': -np.mean(rmse_scores),
        'RMSE (std)': np.std(rmse_scores)
    }

pd.DataFrame(results).T.sort_values('RMSE (CV mean)')

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
import numpy as np
import pandas as pd

# Additional libraries
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

# Sample for faster CV
X_train_sample = X_train.sample(10000, random_state=42)
y_train_sample = y_train.loc[X_train_sample.index]

# Define 6 models
models = {
    'LinearRegression': LinearRegression(),
    'RandomForest': RandomForestRegressor(n_estimators=50, max_depth=5, random_state=42),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=50, max_depth=5, random_state=42),
    'XGBoost': XGBRegressor(n_estimators=50, max_depth=5, learning_rate=0.1, random_state=42),
    'LightGBM': LGBMRegressor(n_estimators=50, max_depth=5, learning_rate=0.1, random_state=42),
    'KNN': KNeighborsRegressor(n_neighbors=5)
}

# Evaluate each model
results = {}
for name, model in models.items():
    pipe = make_pipeline(preprocessor, model)
    rmse_scores = cross_val_score(pipe, X_train_sample, y_train_sample, cv=3, scoring='neg_root_mean_squared_error', n_jobs=-1)
    results[name] = {
        'RMSE (CV mean)': -np.mean(rmse_scores),
        'RMSE (std)': np.std(rmse_scores)
    }

# Display results
pd.DataFrame(results).T.sort_values('RMSE (CV mean)')

from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

# Define base pipeline
from sklearn.pipeline import Pipeline

pipe = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('regressor', XGBRegressor(random_state=42))
])

# Define hyperparameter grid
param_grid = {
    'regressor__n_estimators': [100, 200],
    'regressor__max_depth': [3, 5, 7],
    'regressor__learning_rate': [0.05, 0.1],
    'regressor__subsample': [0.8, 1.0]
}

# Grid search
grid_search = GridSearchCV(pipe, param_grid, cv=3,
                           scoring='neg_root_mean_squared_error',
                           n_jobs=-1, verbose=1)

# Run on sampled data to save time
grid_search.fit(X_train_sample, y_train_sample)

# Best model
print("Best parameters:", grid_search.best_params_)
print("Best RMSE (CV):", -grid_search.best_score_)

# Final model
best_model = grid_search.best_estimator_

# Fit on full training set
best_model.fit(X_train, y_train)

# Predict on test set
y_pred = best_model.predict(X_test)

# Final performance metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Predictions
y_pred = best_model.predict(X_test)

# Metrics
rmse = np.sqrt(mean_squared_error(y_test, y_pred))  # Manually take square root
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Test RMSE: {rmse:.2f}")
print(f"Test MAE: {mae:.2f}")
print(f"Test R²: {r2:.4f}")

import numpy as np

# ----------------------------------------
# STEP 1: PRICE DEVIATION FROM GROUP AVERAGE
# ----------------------------------------

# Calculate average price for each unique (Brand, Model, Year) combination
group_avg_price = df.groupby(['Brand', 'model', 'year'])['price'].transform('mean')

# If a car is cheaper than average → positive score (likely to sell)
df['price_deviation'] = (group_avg_price - df['price']) / group_avg_price

# ----------------------------------------
# STEP 2: POPULARITY SCORE BASED ON RELIABILITY & MILEAGE
# ----------------------------------------

# Define brand reliability scores (0 to 1 scale)
brand_reliability = {
    'Toyota': 0.9, 'Honda': 0.85, 'Ford': 0.7, 'Mercedes': 0.5,
    'Jaguar': 0.4, 'BMW': 0.6, 'Hyundai': 0.75, 'Kia': 0.8,
    'VW': 0.65, 'Vauxhall': 0.7, 'Audi': 0.55, 'Nissan': 0.78
}

# Assign reliability score to each car
df['brand_score'] = df['Brand'].map(brand_reliability).fillna(0.6)  # default = 0.6 if brand missing

# Normalize mileage: low mileage = more desirable = higher score
df['mileage_normalized'] = 1 - (df['mileage'] / df['mileage'].max())

# Combine brand reliability and mileage to form a popularity score
# We give more weight to brand reputation (60%) than mileage (40%)
df['popularity_score'] = 0.6 * df['brand_score'] + 0.4 * df['mileage_normalized']

# ----------------------------------------
# STEP 3: FINAL SALE PROBABILITY USING SIGMOID FUNCTION
# ----------------------------------------

# Define sigmoid function to map raw score to [0, 1] probability
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Set weights for price deviation and popularity
alpha = 2  # weight for price deviation
beta = 1   # weight for popularity

# Compute raw score using weighted sum
df['raw_sale_score'] = (alpha * df['price_deviation']) + (beta * df['popularity_score'])

# Convert raw score to probability
df['sale_probability'] = sigmoid(df['raw_sale_score'])

# ----------------------------------------
# OPTIONAL: Review Distribution
# ----------------------------------------
print(df['sale_probability'].describe())

# Use same features as before
X_prob = df.drop(columns=['price', 'sale_probability', 'sale_likely', 'raw_sale_score'], errors='ignore')
y_prob = df['sale_probability']

from sklearn.model_selection import train_test_split

Xpr_train, Xpr_test, ypr_train, ypr_test = train_test_split(
    X_prob, y_prob, test_size=0.2, random_state=42
)

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.pipeline import make_pipeline
import pandas as pd
import numpy as np

# Sample for speed
Xpr_sample = Xpr_train.sample(10000, random_state=42)
ypr_sample = ypr_train.loc[Xpr_sample.index]

# Define models
models = {
    'LinearRegression': LinearRegression(),
    'RandomForest': RandomForestRegressor(n_estimators=50, max_depth=5, random_state=42),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=50, max_depth=5, random_state=42),
    'XGBoost': XGBRegressor(n_estimators=50, max_depth=5, learning_rate=0.1, random_state=42),
    'LightGBM': LGBMRegressor(n_estimators=50, max_depth=5, learning_rate=0.1, random_state=42),
    'KNN': KNeighborsRegressor(n_neighbors=5)
}

results_prob = {}
for name, model in models.items():
    pipe = make_pipeline(preprocessor, model)
    scores = cross_val_score(pipe, Xpr_sample, ypr_sample, cv=3,
                             scoring='neg_root_mean_squared_error', n_jobs=-1)
    results_prob[name] = {
        'RMSE (CV mean)': -np.mean(scores),
        'RMSE (std)': np.std(scores)
    }

pd.DataFrame(results_prob).T.sort_values('RMSE (CV mean)')

from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

# Base pipeline
pipe_prob = make_pipeline(preprocessor, XGBRegressor(random_state=42))

# Hyperparameter grid
param_grid_prob = {
    'xgbregressor__n_estimators': [100, 200],
    'xgbregressor__max_depth': [3, 5, 7],
    'xgbregressor__learning_rate': [0.05, 0.1],
    'xgbregressor__subsample': [0.8, 1.0]
}

# Grid search
grid_search_prob = GridSearchCV(
    pipe_prob,
    param_grid_prob,
    cv=3,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1,
    verbose=1
)

# Fit on sample for speed
grid_search_prob.fit(Xpr_sample, ypr_sample)

# Show best params
print("Best parameters:", grid_search_prob.best_params_)
print("Best RMSE (CV):", -grid_search_prob.best_score_)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Final model
best_model_prob = grid_search_prob.best_estimator_

# Fit on full training data
best_model_prob.fit(Xpr_train, ypr_train)

# Predict on test set
ypr_pred = best_model_prob.predict(Xpr_test)

# Final evaluation
rmse = np.sqrt(mean_squared_error(ypr_test, ypr_pred))
mae = mean_absolute_error(ypr_test, ypr_pred)
r2 = r2_score(ypr_test, ypr_pred)

print(f"Test RMSE: {rmse:.4f}")
print(f"Test MAE: {mae:.4f}")
print(f"Test R²: {r2:.4f}")

from sklearn.metrics import precision_score, recall_score, f1_score

# Convert probabilities to binary (1 if > 0.5, else 0)
ypr_pred_binary = (ypr_pred > 0.5).astype(int)
ypr_test_binary = (ypr_test > 0.5).astype(int)

# Calculate classification metrics
precision = precision_score(ypr_test_binary, ypr_pred_binary)
recall = recall_score(ypr_test_binary, ypr_pred_binary)
f1 = f1_score(ypr_test_binary, ypr_pred_binary)

print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

!pip install shap lime --quiet

import shap
import pandas as pd

# Extract from pipeline
regressor_price = best_model.named_steps['regressor']
preprocessor_price = best_model.named_steps['preprocessing']

# Transform and convert to DataFrame with correct column names
X_test_transformed = preprocessor_price.transform(X_test).toarray()
feature_names = preprocessor_price.get_feature_names_out()
X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=feature_names)

# SHAP
explainer_price = shap.Explainer(regressor_price, X_test_transformed_df)
shap_values_price = explainer_price(X_test_transformed_df)

# Plot with real feature names
shap.summary_plot(shap_values_price, X_test_transformed_df)

import shap
import pandas as pd

# Extract and transform
regressor_sale = best_model_prob.named_steps['xgbregressor']
preprocessor_sale = best_model_prob.named_steps['columntransformer']
Xpr_test_transformed = preprocessor_sale.transform(Xpr_test).toarray()
feature_names_sale = preprocessor_sale.get_feature_names_out()
Xpr_test_df = pd.DataFrame(Xpr_test_transformed, columns=feature_names_sale)

# SHAP
explainer_sale = shap.Explainer(regressor_sale, Xpr_test_df)
shap_values_sale = explainer_sale(Xpr_test_df)

# Plot
shap.summary_plot(shap_values_sale, Xpr_test_df)

# Local SHAP explanation for price prediction
shap.plots.waterfall(shap_values_price[10], max_display=10)  # change index if needed

# Local SHAP explanation for sale probability
shap.plots.waterfall(shap_values_sale[12], max_display=10)  # change index if needed

import lime.lime_tabular

# LIME with preprocessed, numeric test set
lime_explainer_sale = lime.lime_tabular.LimeTabularExplainer(
    Xpr_test_df.values,
    feature_names=Xpr_test_df.columns.tolist(),
    mode='regression'
)

# Explain a specific prediction (e.g., index 12)
lime_exp_sale = lime_explainer_sale.explain_instance(
    Xpr_test_df.iloc[12].values,
    best_model_prob.named_steps['xgbregressor'].predict
)

# Show result in notebook
lime_exp_sale.show_in_notebook()

# Get SHAP values for sold cars (predicted probability >= 0.5)
ypr_pred_prob = best_model_prob.predict(Xpr_test)
sold_mask = ypr_pred_prob >= 0.5

shap.summary_plot(shap_values_sale[sold_mask], Xpr_test_df[sold_mask])

# Get SHAP values for unsold cars (predicted probability < 0.5)
unsold_mask = ypr_pred_prob < 0.5

shap.summary_plot(shap_values_sale[unsold_mask], Xpr_test_df[unsold_mask])

# Save SHAP plot as PNG for your report
import matplotlib.pyplot as plt

shap.summary_plot(shap_values_price, X_test_transformed_df, show=False)
plt.savefig("shap_summary_price.png", bbox_inches='tight')

shap.summary_plot(shap_values_sale, Xpr_test_df, show=False)
plt.savefig("shap_summary_saleprob.png", bbox_inches='tight')

from sklearn.inspection import PartialDependenceDisplay
import matplotlib.pyplot as plt

features = ['mileage', 'year', 'engineSize']
PartialDependenceDisplay.from_estimator(best_model, X_test, features)
plt.show()